# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-21 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_sessiontoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='privilege',
            old_name='access_all_read',
            new_name='all_delete',
        ),
        migrations.RenameField(
            model_name='privilege',
            old_name='access_all_verify',
            new_name='all_read',
        ),
        migrations.RenameField(
            model_name='privilege',
            old_name='access_all_write',
            new_name='all_verify',
        ),
        migrations.RenameField(
            model_name='privilege',
            old_name='access_company_read',
            new_name='all_write',
        ),
        migrations.RenameField(
            model_name='privilege',
            old_name='access_company_verify',
            new_name='company_delete_documents',
        ),
        migrations.RenameField(
            model_name='privilege',
            old_name='access_company_write',
            new_name='company_delete_transactions',
        ),
        migrations.AddField(
            model_name='privilege',
            name='company_read_documents',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='privilege',
            name='company_read_transactions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='privilege',
            name='company_verify_documents',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='privilege',
            name='company_verify_transactions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='privilege',
            name='company_write_documents',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='privilege',
            name='company_write_transactions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='privilege',
            name='user_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='privilege',
            name='user_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='privilege',
            name='user_verify',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='privilege',
            name='user_write',
            field=models.BooleanField(default=False),
        ),
    ]
