# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-14 10:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('verify_passport', models.BooleanField(default=False)),
                ('verify_govt_id', models.BooleanField(default=False)),
                ('live_image', models.BooleanField(default=False)),
                ('verify_nric_ica', models.BooleanField(default=False)),
                ('verify_billing_address', models.BooleanField(default=False)),
                ('verify_mobile_number', models.BooleanField(default=False)),
                ('track_expiry', models.BooleanField(default=False)),
                ('follow_up_request', models.BooleanField(default=False)),
                ('network_sharing', models.BooleanField(default=False)),
                ('fast_verification', models.BooleanField(default=False)),
                ('phone_interviews', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price_per_user', models.DecimalField(decimal_places=4, max_digits=10)),
                ('date_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_end', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.Service')),
            ],
        ),
    ]
