# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-14 09:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesubscription',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.Service'),
        ),
        migrations.AlterField(
            model_name='servicesubscription',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
