# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-14 00:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=500)),
                ('country', models.CharField(max_length=100)),
                ('verification_field', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('verify_passport', models.BooleanField(default=False)),
                ('verify_govt_id', models.BooleanField(default=False)),
                ('live_image', models.BooleanField(default=False)),
                ('verify_nric_ica', models.BooleanField(default=False)),
                ('verify_billing_address', models.BooleanField(default=False)),
                ('verify_mobile_number', models.BooleanField(default=False)),
                ('track_expiry', models.BooleanField(default=False)),
                ('follow_up_request', models.BooleanField(default=False)),
                ('network_sharing', models.BooleanField(default=False)),
                ('fast_verification', models.BooleanField(default=False)),
                ('phone_interviews', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ui_type', models.CharField(default='single', max_length=30)),
                ('transaction_token', models.CharField(max_length=30)),
                ('js_result', models.CharField(max_length=30)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_completed', models.DateTimeField(default=django.utils.timezone.now)),
                ('version', models.CharField(max_length=10)),
                ('user_ip', models.CharField(max_length=15)),
                ('company_ip', models.CharField(max_length=15)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.Service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
