# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-14 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='document_type',
            field=models.ManyToManyField(to='transactions.DocumentType'),
        ),
    ]
