# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-14 09:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_auto_20160914_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='company',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='companies.Company'),
            preserve_default=False,
        ),
    ]
