# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-14 06:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0002_transaction_document_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocPassport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('version', models.CharField(max_length=10)),
                ('verified', models.BooleanField(default=False)),
                ('date_verified', models.DateTimeField(blank=True)),
                ('document_image', models.CharField(max_length=30)),
                ('document_filename', models.CharField(max_length=100)),
                ('document_filename2', models.CharField(max_length=100)),
                ('parsed_passport_id', models.CharField(blank=True, max_length=100)),
                ('parsed_first_name', models.CharField(blank=True, max_length=100)),
                ('parsed_last_name', models.CharField(blank=True, max_length=100)),
                ('parsed_nationality', models.CharField(blank=True, max_length=100)),
                ('parsed_dob', models.DateTimeField(blank=True)),
                ('parsed_issue_date', models.DateTimeField(blank=True)),
                ('parsed_expiry_date', models.DateTimeField(blank=True)),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.DocumentType')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.Transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
