# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-14 10:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('version', models.CharField(max_length=10)),
                ('verified', models.BooleanField(default=False)),
                ('date_verified', models.DateTimeField(blank=True)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('dob', models.DateTimeField(blank=True, null=True)),
                ('mobile', models.CharField(blank=True, max_length=100)),
                ('home', models.CharField(blank=True, max_length=100)),
                ('other', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocPassport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('version', models.CharField(max_length=10)),
                ('verified', models.BooleanField(default=False)),
                ('date_verified', models.DateTimeField(blank=True)),
                ('document_image', models.CharField(max_length=30)),
                ('document_filename', models.CharField(max_length=100)),
                ('document_filename2', models.CharField(max_length=100)),
                ('parsed_passport_id', models.CharField(blank=True, max_length=100)),
                ('parsed_first_name', models.CharField(blank=True, max_length=100)),
                ('parsed_last_name', models.CharField(blank=True, max_length=100)),
                ('parsed_nationality', models.CharField(blank=True, max_length=100)),
                ('parsed_dob', models.DateTimeField(blank=True, null=True)),
                ('parsed_issue_date', models.DateTimeField(blank=True, null=True)),
                ('parsed_expiry_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
