# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-14 09:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0003_auto_20160914_0920'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('version', models.CharField(max_length=10)),
                ('verified', models.BooleanField(default=False)),
                ('date_verified', models.DateTimeField(blank=True)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('dob', models.DateTimeField(blank=True)),
                ('mobile', models.CharField(blank=True, max_length=100)),
                ('home', models.CharField(blank=True, max_length=100)),
                ('other', models.CharField(blank=True, max_length=100)),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.DocumentType')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.Transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
