# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-14 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_auto_20160914_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docform',
            name='date_verified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='docpassport',
            name='date_verified',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
