# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-15 09:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('documents', '0005_userdocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdocument',
            name='doc_id',
        ),
        migrations.RemoveField(
            model_name='userdocument',
            name='doc_type',
        ),
        migrations.AddField(
            model_name='userdocument',
            name='document_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdocument',
            name='document_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
