# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-20 00:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_auto_20160915_1024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='docform',
            old_name='user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='docpassport',
            old_name='user',
            new_name='owner',
        ),
    ]
