# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-22 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_auto_20160921_0223'),
        ('documents', '0008_auto_20160920_0001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docform',
            name='transaction',
        ),
        migrations.AddField(
            model_name='docform',
            name='transaction',
            field=models.ManyToManyField(blank=True, null=True, to='transactions.Transaction'),
        ),
        migrations.RemoveField(
            model_name='docpassport',
            name='transaction',
        ),
        migrations.AddField(
            model_name='docpassport',
            name='transaction',
            field=models.ManyToManyField(blank=True, null=True, to='transactions.Transaction'),
        ),
    ]
