# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-22 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_auto_20160922_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docform',
            name='transaction',
            field=models.ManyToManyField(blank=True, to='transactions.Transaction'),
        ),
        migrations.AlterField(
            model_name='docpassport',
            name='transaction',
            field=models.ManyToManyField(blank=True, to='transactions.Transaction'),
        ),
    ]
