# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-23 00:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_auto_20160921_0223'),
        ('documents', '0011_auto_20160922_0916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docform',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='docform',
            name='date_verified',
        ),
        migrations.RemoveField(
            model_name='docform',
            name='document_type',
        ),
        migrations.RemoveField(
            model_name='docform',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='docform',
            name='transactions',
        ),
        migrations.RemoveField(
            model_name='docform',
            name='verified',
        ),
        migrations.RemoveField(
            model_name='docform',
            name='version',
        ),
        migrations.RemoveField(
            model_name='docpassport',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='docpassport',
            name='date_verified',
        ),
        migrations.RemoveField(
            model_name='docpassport',
            name='document_type',
        ),
        migrations.RemoveField(
            model_name='docpassport',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='docpassport',
            name='transactions',
        ),
        migrations.RemoveField(
            model_name='docpassport',
            name='verified',
        ),
        migrations.RemoveField(
            model_name='docpassport',
            name='version',
        ),
        migrations.AddField(
            model_name='userdocument',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='userdocument',
            name='transactions',
            field=models.ManyToManyField(blank=True, related_name='documents', to='transactions.Transaction'),
        ),
        migrations.AddField(
            model_name='userdocument',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
