# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-23 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_auto_20160923_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdocument',
            name='version',
            field=models.CharField(default='v0', max_length=10),
            preserve_default=False,
        ),
    ]
