# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-14 09:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('white_label', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('date_registered', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date registered')),
            ],
        ),
    ]
